### ISSUE TITLE
Lobby size in the lobby page

### ISSUE THREAD

**Issue by NicoSerranoP** [zkparty/trusted-setup-frontend#100]
Show participants how many people are waiting. Use the `/info/state` sequencer route

**Comment by tvanepps** [comment]
maybe we should also display this information in the landing page nav bar, next to the sequencer status

there should also be a a rough average "wait time" based of how much time each contribution takes. if needed, we can put in a dummy value and tune it over time. just something that gives people a rough idea how long they should expect to wait
