### ISSUE TITLE
Tweet text in test site should mention that it's a test contribution 

### ISSUE THREAD

**Issue by glamperd** [zkparty/trusted-setup-frontend#102]
Temporary change to the tweet intent text to make it clear that it's a test run.

**Comment by NicoSerranoP** [comment]
We have the following text
`I just contributed to the test KZG Ceremony to scale Ethereum using {{identity}}`

[https://github.com/zkparty/trusted-setup-frontend/blob/main/src/locales/en/translation.json#L23](url)

We could put "test" in uppercase but we would have to change it in all languages (right now 16). I will be checking out that all labels appears in all languages.json files, I will could try to put it in uppercase then

**Comment by glamperd** [comment]
> We have the following text `I just contributed to the test KZG Ceremony to scale Ethereum using {{identity}}`
> 
> [https://github.com/zkparty/trusted-setup-frontend/blob/main/src/locales/en/translation.json#L23](url)
> 
> We could put "test" in uppercase but we would have to change it in all languages (right now 16). I will be checking out that all labels appears in all languages.json files, I will could try to put it in uppercase then

It's not critical that this be translated. We could put an untranslated text, e.g., `**TEST**` before the translatable text.

**Comment by NicoSerranoP** [comment]
Done! I just added the **TEST** :D [https://github.com/zkparty/trusted-setup-frontend/blob/main/src/components/modals/ContributionModal.tsx#L76](url)
