### ISSUE TITLE
URL Card preview

### ISSUE THREAD

**Issue by tvanepps** [zkparty/trusted-setup-frontend#107]
sharing the ceremony.ethereum.org URL should produce a preview card similar to the image below. as a stretch, it would be nice if it had a dynamic display which shared the total number of complete contributions at that time (not a priority at this time). im not entirely sure how to configure this on the site, carl might have an idea

![image](https://user-images.githubusercontent.com/27454964/207423380-f1742f07-562a-491d-af6c-4dbb4a98716e.png)

we can use this image for the preview card for now, let me know if you need any modifications to ratio/ otherwise

<img width="2000" alt="KZG preview card" src="https://user-images.githubusercontent.com/27454964/207457832-25c2a4f7-3ded-4ca9-aa2e-bb903325e57b.png">

**Comment by CarlBeek** [comment]
This card is implemented in #113. Unfortunately dynamic rendering of queue length etc requires sever-side rendering which is not something we currently do (nor plan to do) for this site.
