### ISSUE TITLE
UI stuff round 3

### ISSUE THREAD

**Issue by tvanepps** [zkparty/trusted-setup-frontend#108]
![image](https://user-images.githubusercontent.com/27454964/207473911-d8be06bf-2144-4551-935a-80816ab2ce3e.png)

1.  [x] -  1) the cursor over this part indicates interaction, but i think it should just be a regular cursor
2. [x] - 2) the dropdown menu should be the same width as the globe <> down arrow (red lines), or at least centered on this group
3. [x] - 3) this area still needs work but at a minimum the tan circle should be centered vertically on the red box of content
4. [x] - 4) can we make this one line instead of two to give the other content more room to breathe
5. [x] - 5) can we add the FAQ section directly to this page and remove it from the footer? adjust other footer elements up
6. [x] - 6) “Built by the Ethereum community - 2022”  given there have been many contributors to this, not just the EF.
7. [x] - 7) the width between these two text lines should be normalized somehow, maybe to the red lines? i believe the top width matches the following pages, but it might be worth breaking in this case
8. [x] - 8) we should consider a small section of “latest contributions” with ~3 of the latest and a button to “View all” that takes you to the existing Contribution transcript interface
9. [x] - 9) we should delete this text - it’s unnecessary. we can wait to delete once we have a more substantial set of text changes to pass to the translation team when we get there
10. [x] - 10) i think this information should be presented to users on the landing page, possibly centered in the toolbar? open to suggestions

![image](https://user-images.githubusercontent.com/27454964/207474093-f7f3d20c-4067-41b3-be3f-609b6fdc5569.png)

11. [x] - 11) move FAQ to the landing page. make sure that the text width of copy aligns with the other copy blocks
12. [x] - 12) hover state and lines between entries should match the contributions page. 
13. [x] - 13) question header should not match page title size/weight (esp after moving it to the home page where there are other headers). i’d make all of these headers bold but the same typeface as the copy itself, just bold

![image](https://user-images.githubusercontent.com/27454964/207480532-946fe897-19e0-4b11-89b4-c0258051bd67.png)
![image](https://user-images.githubusercontent.com/27454964/207474186-b9a40680-7fae-4069-928a-7d2dc79a48cc.png)

this page is looking really good! great work  

13. [x] - 13) 1 need a higher contrast color for the loading indicator, match whatever is decided elsewhere
14. [x] - 14) add an option to toggle between oldest / newest
15. [x] - 15) align text with other elements below
16. [x] - 16) we need to add some context in the genesis modal explaining why this contribution is this way
17. [x] - 17) shouldn’t this show the last page # instead of 6? ie, there are 34 pages right now, how can a user skip to the end? if we implement #14, then this becomes less of an issue
18. [x] - 18) minor, but didn’t we talk about omitting ENS from search bc it might change owners in the future?
19. [x] - 19) change background to tan #FFF8E7
20. [x] - 20) the tooltip aid should expand into the right margin, not over another contribution. the triangle pointer overlaps  “fingerprint”. tooltip text should be 2 or three lines, possibly the size of the red rectangle

![image](https://user-images.githubusercontent.com/27454964/207474260-5a8145c8-0234-461e-b1f6-358c0073748f.png)

just a thought, should these contribution modal layouts match the one available at the “dankshard draws near”? (edit: just realizing that that's the "sequencer acknowledgment" - i didn't realize they were different things and other people probably wont. it would be good to add some introduction text explaining why this page is important.)

**Comment by NicoSerranoP** [comment]
4. The translation files are finished and the breakpoint in "SUMMONING GUIDE" is embed in the translations. We would need to change the 17 files. Also, I prefer the two lines, check how it looks in one:
![image](https://user-images.githubusercontent.com/38594836/207719084-8d20cb47-29bb-4852-98f4-80bc99b33b84.png)


**WORK IN PROGRESS:** please wait until I put all observations in this comment. I will remove this paragraph when it is done
