### ISSUE TITLE
UI changes round 4

### ISSUE THREAD

**Issue by tvanepps** [zkparty/trusted-setup-frontend#109]
![image](https://user-images.githubusercontent.com/27454964/207478033-c94a23a2-7c3e-4b42-bd43-6b983aee2504.png)

- [x] 1. the text entropy section cursor changes to be smaller and bold, the hidden text is no longer centered in the entry box

![image](https://user-images.githubusercontent.com/27454964/207478552-3043acbb-9230-4d62-b3b4-28b4d0169f73.png)

- [x] 2. if the user zooms below 100%, it shouldn't look cut off. we should be using the full graphic for each step
- [x] 3. the white space between the top and bottom should be visually balanced

![image](https://user-images.githubusercontent.com/27454964/207478827-afc656cc-e9fd-43bf-903a-93f859b9d26a.png)

- [x] 4. blue on yellow is not going to be visible, use a higher contrast color for the spinning wheel. we should also consider some prompt of "check your wallet to sign"

![image](https://user-images.githubusercontent.com/27454964/207479138-2f904060-882f-4520-b525-adb633d29ce8.png)

- [x] 5. change background to tan #FFF8E7 - the end of the contrbution, the entire page should be saturated
- [x] 6. move "share on twitter" button to here so participants are prompted early. make sure to give proper balance whitespace once it's added
~~ separate note, but we need to improve this text to better communicate what happens after the ceremony, when it will be used

![image](https://user-images.githubusercontent.com/27454964/207483196-33b6cea6-77f2-47c8-afd8-ccbb703ad0d9.png)

i think we should consider reformatting from a long horizontal modal to a square/ vertical rectangle - stacking “My keys” above “sequencer acknowledgment” and add a scroll if necessary, similarly for the other transcript modal  

- [x] 7. 1. can we add a link in a new window to the full transcript?
- [x] 8. should be “Participant ID” for consistency
- [x] 9. try to reproduce the suggestions from the other modal if possible
- [x] 10. align text with red line (signed by, integrity checks)
- [x] 11. needs more info telling the participant what an integrity check is, what happens if it fails
- [x] 12. remove, put on previous page
- [x] 13. can users download the receipt as a txt file, not json? not sure if there is a specific reason for json, txt just seems more user friendly

edit Dec 16 3:48 ET - an idea on what the modal could look like.

![image](https://user-images.githubusercontent.com/27454964/208186451-1ce9135f-1a6a-4cfb-bffa-01175930363a.png)

**Comment by NicoSerranoP** [comment]
1.- We are using a special font family to "hide" the secret text input without making the browser trigger the "Save your password" popup that appears when a secret/password text is entered. It is difficult to prevent the bold cursor (I am still trying to find a way but I don't know how).

**WORK IN PROGRESS**: please wait until I put all observations in this comment. I will remove this paragraph when it is done
