### ISSUE TITLE
UI changes - round 5

### ISSUE THREAD

**Issue by tvanepps** [zkparty/trusted-setup-frontend#117]
![image](https://user-images.githubusercontent.com/27454964/210297145-b95a048c-e9cf-4271-8bc4-224a27a56040.png)

- [x] 1. background color should be #FFF8E7, remove gradient circle behind text 
- [x] 2. use the border design suggested in the figma doc for the intro content, the “Latest Contribution” section, and the FAQ 
   - trent to update design
- [x] 3. make header text single line, we can update translations later
- [x]  4. add countdown suggested in figma doc  between title and copy
- [x] 5. delete button and text, these are not needed anymore. be sure to reapportion leftover whitespace 
- [x] 6.  users should be able to click through to the link anywhere within that red box, not just on the text. the links should also go to: 
- IPFS: https://github.com/ethereum/kzg-ceremony/blob/main/README.md#ipfs-hosted-versions (i can point kzgceremony.eth to these hashes)
- Hosted Interface: https://ceremony.ethereum.org/#/entropy_input
- Other clients: correct link
- Write your own: https://blog.ethereum.org/2022/12/15/kzg-ceremony-grants-round 
- [x] 7. hover states/ border not consistent between each button. second blue border should be further in if size of font allows for it, see figma for reference

![image](https://user-images.githubusercontent.com/27454964/210297411-55323194-214e-431d-b394-73a1bb960886.png)

- [x] 8. Use bold Inter copy font for FAQ headers, not Taviraj. also, if possible we should tighten the whitespace around each FAQ (red line suggestion), make sure to apply to all FAQs, not just the last one. not a priority, but on hover state for the FAQs, everything below moves up a few pixels because the bottom line is removed. time permitting, this should not happen 
- [x] 9. “Built”, not “Build”

![image](https://user-images.githubusercontent.com/27454964/210297480-b6f4c5c1-96da-4b1e-b6af-564b6f9346b0.png)

- [x] 10. ❓do we even need the nav bar at this point if we’re removing the arrow? it would be cleaner without it. if people want to change the language they could just do this at the beginning. or we can keep the language dropdown in the corner but still remove the white bar. not a strong opinion, and not a huge priority (this would apply to all steps of the hosted interface after this one as well)  
- [x] 11. remove green around cursor - seems to be a bit laggy in my experience, and doesn’t fit with the rest of the graphic theme
- [x]  12. any context on what the wait icon is for?

![image](https://user-images.githubusercontent.com/27454964/210297637-bbaae0fe-f344-4ee3-bb27-61e81c465bb0.png)

- [x] 13. remove arrow to be consistent with the previous page. (realizing now the arrow might be an antipattern if we encourage people to do it, the site might time out if they do it at a certain point in the flow)  
- [x] 14. hover shadow characteristics (placement, spread, opacity) for all applications (including buttons) should be the same as elsewhere eg. landing page options, FAQ, Transcript contributions. here it is too light. not a high priority
- [x] 15. add underline and ↗ to indicate a link out

![image](https://user-images.githubusercontent.com/27454964/210297709-261c74cf-a129-45fc-a4a9-1a94bc21c472.png)

- [x] 16. remove arrow as in previous steps  
- [x] 17. ❓perhaps the text should note “After signing with a wallet, you will be redirected to a “Sign-in with Ethereum" page, and then back here to complete the process of contribution.” it’s a little strange to be redirected without notice after signing the first time in the wallet.
- [x] 18.   content should ideally be centered vertically in the circle
- [x] 19. move addition of yellow ring to the previous step in the flow to distribute the color between the steps better

![image](https://user-images.githubusercontent.com/27454964/210297842-ff72c5d7-2a2f-40d4-9bb7-3b67aea53797.png)

- [x] 20. move the computation pulse animation (where the shields become yellow) to this lobby step and just keep it consistent until the completion of the calculation / “Dankshard draws Near”
- [x] 21. the disk animation / color should be moved to the previous step but without the spinning animation. 1. this will help spread out the appearance of color throughout all the steps. 2. i’d like it to not move because the spinning exposes disconnected areas under the graphic that it wasn’t designed for

![image](https://user-images.githubusercontent.com/27454964/210297951-fa6682a2-48b9-421b-a773-26e2d2990225.png)

- [x] 22. i should have been more specific - this should link to the hosted records interface at https://ceremony.ethereum.org/#/record

![image](https://user-images.githubusercontent.com/27454964/210297973-410fb1a2-c1e0-411f-adc4-0b64a33bb773.png)

- [x] 23. integrity check info is anchored to the wrong place  
- [x] 24. the bottom of the “View Contribution” ends with the bottom of the page, which feels a bit odd. the user should be able to scroll a bit further so “Download receipt” is slightly higher on the page

![image](https://user-images.githubusercontent.com/27454964/210298033-63918001-f5f0-4e7c-9c99-77936d397c00.png)

- [x] 25. clicking the “View all Contributions” button on the homepage takes you to the bottom of the records page, not the top

![image](https://user-images.githubusercontent.com/27454964/210298089-4d4e8bf4-afdf-4a52-aac5-f448dd2768a2.png)

- [x] 26. each data point should be a newline for visual clarity and other languages. suggestion on the right

![image](https://user-images.githubusercontent.com/27454964/210298143-25d6cffd-8486-4f31-a7b7-006215e61828.png)

- [x] 27. minor text alignment issues on the homepage - seen with simple english, french, spanish. not sure the cause

**Comment by NicoSerranoP** [comment]
12. In the Entropy Input page we are computing the PoT pubkeys that might be needed to be double signed with a wallet provider. In some computers it might take a little longer to compute, in this situation we get the waiting icon for a couple of seconds and we hide the button to avoid double clicking on it

**Work in Progress:** I will delete this line after addressing the observation clarifications for specific points. Please wait until then to have the final version
