### ISSUE TITLE
FAQ Titles/Questions don't translate

### ISSUE THREAD

**Issue by CarlBeek** [zkparty/trusted-setup-frontend#118]
When using a language other than `English`, the questions in the FAQ section don't change language. 

e.g. in German:

> **Couldn’t another commitment scheme without a "trusted setup" be used?**
> 
> Mit einem anderen Mechanismus als KZG (z. B. IPA oder SHA256) wäre die Sharding-Roadmap viel schwieriger umzusetzen. Weitere Informationen finden Sie im [FAQ zu Proto-Danksharding](https://notes.ethereum.org/@vbuterin/proto_danksharding_faq#Couldn%E2%80%99t-we-use-some-other-commitment-scheme-without-a-trusted-setup) von Vitalik.

**Comment by NicoSerranoP** [comment]
I fixed it here [https://github.com/zkparty/trusted-setup-frontend/commit/9ba44933c14b745d9c954aefd484971a6567f021](https://github.com/zkparty/trusted-setup-frontend/commit/9ba44933c14b745d9c954aefd484971a6567f021)

Will merge it with the other UI changes this week :)
