### ISSUE TITLE
COOP + OAuth popups in Firefox

### ISSUE THREAD

**Issue by NicoSerranoP** [zkparty/trusted-setup-frontend#12]
It is not working and there is no trial token as in Chrome

**Comment by NicoSerranoP** [comment]
To activate HTTP headers in React development stage, create a `/src/setupProxy.js` file with the following content:
```
module.exports = function(app) {
    app.use(function(req, res, next) {
      res.header("Access-Control-Allow-Origin", "*");
      //res.header("Cross-Origin-Embedder-Policy", "require-corp");
      //res.header("Cross-Origin-Opener-Policy", "same-origin-allow-popups");
      next();
    });
  };
```

Remember to start the app using `npm start` instead of `yarn start`

**Comment by glamperd** [comment]
We are considering an alternative approach: simply redirect to the OAuth sign-in  page for all browsers, then have it redirect to us upon completion.
