### ISSUE TITLE
UI round 6 review

### ISSUE THREAD

**Issue by tvanepps** [zkparty/trusted-setup-frontend#130]
![image](https://user-images.githubusercontent.com/27454964/211895437-192b096f-347e-4af6-800a-0b5f8dd99a76.png)

- [ ] 1. this is one that’s been around for a while, but the key icons from the first circle is missing for some reason and appears only after submitting.
- [x] 2. size of loading indicator is too large, throws off vertical centering. if we can omit that would be ideal, if not make smaller

![image](https://user-images.githubusercontent.com/27454964/211896788-99dce6c6-c902-47b0-9971-e031fe3076e4.png) 
- [x] 3. size of modal is too large relative the components it frames
- [x] 4. “share on” is redundant given the title, only needs the name itself eg. "Twitter", "Lenster". also - clicking either one of these buttons also opens two new tabs for both. should only produce a new tab for the one chosen

**Comment by NicoSerranoP** [comment]
1. I think that the design was meant that way. No keys before entropy input, keys appear after that step. Look at the Figma:
![image](https://user-images.githubusercontent.com/38594836/211995001-b648be8b-c73d-4f25-83d1-d4249305fd3c.png)
