### ISSUE TITLE
UX review

### ISSUE THREAD

**Issue by hanniabu** [zkparty/trusted-setup-frontend#131]
This is a review of some UX issues I've noticed when revisiting the site since a few weeks ago. These issues have been confirmed by others in the Rocket Pool community. The main issues revolved around no clear call to actions and the user being unsure of what to do.

Left: original; Right: simple improvement suggestions
![summoning](https://i.imgur.com/29bYlq6.png)

**Summoning Landing Page**
- Many people, including myself, don't read. If there's no obvious action then many will leave. Here, the call to action "Choose one of the paths below to begin the ritual:" is "hidden" in the paragraph text. To resolve this, I suggest pulling it out into its own line, separating it more than the standard paragraph gap, and capitalize and bold it to draw attention to it.
- For the options, I understand the goal of wanting diversity. However, it also introduces indecision as well as confusion (see next point). Most normal users won't have the ability or desire to setup their own local instance of these alternative interfaces, so I suggest simply adding "Recommended" to the hosted option as that's what would apply to most users. 
- For the IPFS interface, it brings you to Github rather than to the IPFS site. And even after going to Github and clicking those links, both links don't work. It appears to be pointing to a Github blob rather than IPFS and it's just returning a 404 page.

Image: simple improvement suggestion
![entropy](https://i.imgur.com/jX1wH9l.png)

**Entropy Page**
- Only one thing here. The first point, "secret", doesn't start with a verb so it makes it unclear what to do. I suggest changing the sentence from "A piece of you in text form..." to "Enter a piece of you in text form..."

I tried making a PR but I didn't know React or the codebase well enough and was having difficulty.

**Comment by NicoSerranoP** [comment]
Thank you @hanniabu ! I feel these are great point outs. @tvanepps what do you think? 

The IPFS issue is because we haven't create a build with the latest update version (we hope to do it tomorrow).

**Comment by NicoSerranoP** [comment]
1. We redesign the home banner to make it more explicit
2. IPFS interface was been updated to the latest build
3. The texts changes are being updated (Work in progress)
