### ISSUE TITLE
Tweet text cuts off last digit of Eth addresses

### ISSUE THREAD

**Issue by glamperd** [zkparty/trusted-setup-frontend#139]
I got this text: `I just contributed to the 🕯️ KZG Ceremony 🕯️ using 0xa2c…c6d to help scale Ethereum ` but my address ends in c69d

**Comment by NicoSerranoP** [comment]
I just push it to main [https://github.com/zkparty/trusted-setup-frontend/commit/c1cfb971fbda3f145765c33355ccb5a25c5d8db8](https://github.com/zkparty/trusted-setup-frontend/commit/c1cfb971fbda3f145765c33355ccb5a25c5d8db8). The fix didn't involve major changes so I just commited directly
