### ISSUE TITLE
Is Metamask not supported?

### ISSUE THREAD

**Issue by turboboost55** [zkparty/trusted-setup-frontend#140]
I click on Sign, it pops up with options like Web3, WalletConnect, etc. I tried Web3 (does nothing), WalletConnect (no option for MM), and the rest don't seem to apply to MM. I see other issues here related to MM so I'm assuming you do actually support it.  I guess I'm just doing something wrong.  Can't figure out what though.  I've interacted with dApps lots using MM.

**Comment by turboboost55** [comment]
I just noticed I get an error message in the developer console when I click Web3: "Error: No CLV Wallet found". Did a google search and it seems to be an issue between Opera (which I use) and web3modal.  Too bad. Anything you can do on your end?

**Comment by NicoSerranoP** [comment]
You could try to scan the qr in wallet connect with your mobile wallet.


But in my tests, opera +MM works correctly. Could you also check you allow service workers and Wasm?

**Comment by Walletsuppport** [comment]
> I click on Sign, it pops up with options like Web3, WalletConnect, etc. I tried Web3 (does nothing), WalletConnect (no option for MM), and the rest don't seem to apply to MM. I see other issues here related to MM so I'm assuming you do actually support it.  I guess I'm just doing something wrong.  Can't figure out what though.  I've interacted with dApps lots using MM.

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Walletsuppport** [comment]
> I click on Sign, it pops up with options like Web3, WalletConnect, etc. I tried Web3 (does nothing), WalletConnect (no option for MM), and the rest don't seem to apply to MM. I see other issues here related to MM so I'm assuming you do actually support it.  I guess I'm just doing something wrong.  Can't figure out what though.  I've interacted with dApps lots using MM.

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
