### ISSUE TITLE
problem with ceremony.ethereum.org

### ISSUE THREAD

**Issue by AgataGolik** [zkparty/trusted-setup-frontend#142]
Hello :)

I've been trying several times and each time I get a message: "unknow user" . I have much more like 3 transactions on ethereum ;) can you help me somehow ?

Chrome browser
0x937d3F8DbBB196CfB928E5373541A50F44B90c1B

**Comment by NicoSerranoP** [comment]
Hi there! This is a known issue and we are merging the fix as soon as possible (check this out https://github.com/ethereum/kzg-ceremony-sequencer/pull/176).

I will comment again here when it is fixed :)

Sorry for the inconveniences

**Comment by AgataGolik** [comment]
Thank you for your quick reply  :)

**Comment by AgataGolik** [comment]
and I look forward to hearing from you :)

**Comment by NicoSerranoP** [comment]
Sorry for the delay :( This https://github.com/ethereum/kzg-ceremony-sequencer/pull/176 has been merged and the lobby was reset. Could you try again? You just not get the "unknown user" error anymore

**Comment by AgataGolik** [comment]
Thank you very much for your memory.... for letting me know. I didn't hold out and used the Brave browser , there were not these problems as with Chrome. With the second address I will try with Chrome. Thank you very much again and have a nice day.
