### ISSUE TITLE
Problems to make my contribution

### ISSUE THREAD

**Issue by Cansito** [zkparty/trusted-setup-frontend#143]
The page shows me the following Unknown user error. Please sign in again with a different account and do not allow me to make the contribution, I have already tried several times and I keep throwing the same.

I’m doing it with this wallet 0x0605C6ce2C21C11E8b0A107c4eA55c966E343367, I used metamask and google chrome browser

**Comment by NicoSerranoP** [comment]
Hi there! This is a known issue and we are merging the fix as soon as possible (check this out https://github.com/ethereum/kzg-ceremony-sequencer/pull/176).

I will comment again here when it is fixed :)

Sorry for the inconveniences

**Comment by NicoSerranoP** [comment]
This https://github.com/ethereum/kzg-ceremony-sequencer/pull/176 has been merged and the lobby was reset. Could you try again?
