### ISSUE TITLE
This wallet has already contributed to the ceremony

### ISSUE THREAD

**Issue by KingZee** [zkparty/trusted-setup-frontend#144]
But I don't see my address in the record (https://ceremony.ethereum.org/#/record)
Is there a problem?

**Comment by NicoSerranoP** [comment]
There is a unknow issue with logouts ([](https://github.com/ethereum/kzg-ceremony-sequencer/pull/176)). As soon as the solution is merge, I will notify you to try again :)

**Comment by NicoSerranoP** [comment]
@KingZee I just noticed that you are referring that you contributed to the ceremony and your contribution is not visible in the records page. Could you help me out with:

1. At what time on Friday 13th you contributed? Remember that we reseted the Test Ceremony on 13:13 UTC.
2. Did you downloaded your JSON receipt just after contributing in the "Dankshard draw near"? Could you upload it here?

**Comment by KingZee** [comment]
I contributed 2 days ago.
And it failed, I had to wait for a lot of people, and I think I completely forgot and picked up my laptop in my bag, probably disconnecting it.
When I opened it again later, I don’t remember exactly but I think it said “Signing failed”.
I refreshed and tried the process again, and it says that I already contributed.
I cleared cookies, cache, local storage, it still gives me the same message.

**Comment by NicoSerranoP** [comment]
Could you share our public address here? the "already contributed" error message might be related to the bug pinned above. I can notify you when the solution is merge so you can try again

**Comment by KingZee** [comment]
It’s kingzee.eth , thanks a lot!

**Comment by KingZee** [comment]
Message:
oidc.signinwithethereum.org wants you to sign in with your Ethereum account:
0x0c9e25F360807DA04549a69baEC94c9fda1D41a7

You are signing-in to seq.ceremony.ethereum.org.

URI: https://oidc.signinwithethereum.org
Version: 1
Chain ID: 1
Nonce: dbpTdjxLiAdcsMVf
Issued At: 2023-01-18T10:16:02.342Z
Expiration Time: 2023-01-20T10:16:02.339Z
Resources:
- https://seq.ceremony.ethereum.org/auth/callback/eth

This is the last thing I sign before I get redirected to "This wallet has already contributed to the ceremony".

**Comment by NicoSerranoP** [comment]
There is no signs of your address in the ceremony transcript, I asked the team to see if we can check out if your address was blacklisted for some reason

**Comment by QEDK** [comment]
Same issue here.

**Comment by NicoSerranoP** [comment]
This [PR](https://github.com/ethereum/kzg-ceremony-sequencer/pull/176) has been merged and the lobby was reset. Could you try again?

**Comment by QEDK** [comment]
> This [PR](https://github.com/ethereum/kzg-ceremony-sequencer/pull/176) has been merged and the lobby was reset. Could you try again?

Same issue still persists.

**Comment by NicoSerranoP** [comment]
@QEDK could you pass me your public address?

**Comment by QEDK** [comment]
> @QEDK could you pass me your public address?

0xqedk.eth

**Comment by NicoSerranoP** [comment]
Hey! We flushed out the blacklist so any address with at least 3 txs before Friday 13th should be able to contribute. Could you try again? :)

**Comment by QEDK** [comment]
> Hey! We flushed out the blacklist so any address with at least 3 txs before Friday 13th should be able to contribute. Could you try again? :)

works now, thanks!
