### ISSUE TITLE
Stuck on bind your contribution

### ISSUE THREAD

**Issue by 2color** [zkparty/trusted-setup-frontend#149]
I'm using wallet connect to sign the message. After signing the message, nothing happens, and the page is stuck.
<img width="651" alt="Screen Shot 2023-01-17 at 5 15 48 PM" src="https://user-images.githubusercontent.com/1992255/212952880-eb43a9bf-f2a3-4340-9026-e7a19ca9341b.png">

One of the reasons this might be happening is because the app is hitting Infura with too many requests (to `https://mainnet.infura.io/v3/86b04963127d42fbbf41d9546de393eb`) which return 429s

**Comment by NicoSerranoP** [comment]
Hi there! Sorry about this. It looks like our Infura services reached the requests limit. Give me a moment I discuss with the team about possible alternatives and I will keep you updated

**Comment by NicoSerranoP** [comment]
Sorry for the delay @2color. Could you try again? The Infura node we are using is now below request limits. If it does not work, could you copy and paste the console log errors here?
