### ISSUE TITLE
This address has already contributed to the Ceremony

### ISSUE THREAD

**Issue by errrstr** [zkparty/trusted-setup-frontend#159]
tell me how this problem is solved, my wallet is not in the general CONTRIBUTIONS 
![ог](https://user-images.githubusercontent.com/123713933/216104452-234eec12-5a8f-4886-88d4-d3e89b9af859.PNG)

**Comment by NicoSerranoP** [comment]
It might be in the blacklist, we will flush it out in a couple of days. I will keep you updated here when it is done.

**Comment by glamperd** [comment]
Duplicate of #160
