### ISSUE TITLE
something went wrong : This address has already contributed to the Ceremony

### ISSUE THREAD

**Issue by goodwaygg44** [zkparty/trusted-setup-frontend#160]
hi 
the contribution was interrupted. It became something went wrong. When i tried to do it again, it said i contributed. But I don't think so. I checked the record, there isnt one. 
what am i supposed to do ?

**Comment by goodwaygg44** [comment]
seems like other people are having same issue. I just wonder if i need to provide my wallet address so it can be removed from blacklist ?

**Comment by hehnajd** [comment]
Same issue here.

**Comment by glamperd** [comment]
Your options are to wait until the blacklist is cleared, then try again with the same address, or to try again with another eligible address.

**Comment by gaohongxiang** [comment]
> Your options are to wait until the blacklist is cleared, then try again with the same address, or to try again with another eligible address.

When will the blacklist be removed? Many people have encountered this problem

**Comment by goodwaygg44** [comment]
> Your options are to wait until the blacklist is cleared, then try again with the same address, or to try again with another eligible address.

so when will it be removed ?

**Comment by NicoSerranoP** [comment]
Hi there! Could you try one more time this week? If it does not work, please send your public address here so we can manually whitelist it

**Comment by 89kkkkk** [comment]
hello, I have been waiting for a month when you remove me from the black list, please do it manually in my wallet 0xA68FF970b3A32e0978Ed78A4f7b0e0ac8DDd1954

**Comment by 89kkkkk** [comment]
earlier also opened the conversation here, thanks in advance sir

**Comment by hehnajd** [comment]
> Hi there! Could you try one more time this week? If it does not work, please send your public address here so we can manually whitelist it

0xb053946fE12b681B0aB485Cc9978fD6F4C04d53e
thank you

**Comment by fokwiz** [comment]
I got error when it was my turn to contribute. Here is my wallet

0xC1C22b5eB6c27a7efc62f039d1524c744820Ab0D

**Comment by bettyy0999** [comment]
0x214083ae21f2dfCB09a6Eab567b8A53F309125ba  same problem help promised to fix

**Comment by bettyy0999** [comment]
same problem help, promised to fix  0x214083ae21f2dfCB09a6Eab567b8A53F309125ba

**Comment by gaohongxiang** [comment]
> Hi there! Could you try one more time this week? If it does not work, please send your public address here so we can manually whitelist it

0x494e3aD6DC1E9070bE09E054bFb809905F95C9F6。Please help me remove the blacklist too, thanks

**Comment by NicoSerranoP** [comment]
@89kkkkk @hehnajd @fokwiz @bettyy0999 @gaohongxiang Your addresses have been removed from the blacklist. Please try again

**Comment by goodwaygg44** [comment]
it did not work for me and my friends. we have the same issue . 
0x1F70eBBd87dbE62f323864c982f89C9E81539574
this is my address. should i provide you my friends' addresses too? should they just sign up github account to contact you themselves or i can do them favour. like 5 of them have the issue

**Comment by gaohongxiang** [comment]
> @89kkkkk @hehnajd @fokwiz @bettyy0999 @gaohongxiang您的地址已从黑名单中删除。请再试一次

I tried again, but still get this error

**Comment by paparai** [comment]
> @89kkkkk @hehnajd @fokwiz @bettyy0999 @gaohongxiang Your addresses have been removed from the blacklist. Please try again

could you please remove from the blacklist this one 0x25AF5554F407c8FE33799877a399754d8E11e79d? thank you in advance

**Comment by hehnajd** [comment]
> @89kkkkk @hehnajd @fokwiz @bettyy0999 @gaohongxiang Your addresses have been removed from the blacklist. Please try again

i tried again ，but it does not work 0xb053946fE12b681B0aB485Cc9978fD6F4C04d53e

**Comment by zzyspace** [comment]
@NicoSerranoP 0x52A4249BaFF6832e336E6aF8d6a50cBA106eeE11, help please. over 10 days in blacklist

**Comment by Mogulcc** [comment]
@NicoSerranoP 0x8cD1D0f24aB5e8DB362194B8034FCC66aed0e86E  thanks for your hard working

**Comment by DrPsychonaut98** [comment]
Until this is figured out this looks like a trainwreck. I WANT to contribute very much so, but the amount of people with this unresolved issue that has existed for an obscene amount of time ar this point leads me to think this is neither worth contributing to atm nor is it a good idea. Obviously the people running this stand capable of despondent with the issues in s timely,  thorough manner. How should I expect the finished product to functioning this is how a simple issue is dealt with?

**Comment by DrPsychonaut98** [comment]
Apologies, I mean no offense, but seriously...what other conclusion should I draw? I hope this is dealt with soon. This is not an acceptable issue for such an "ambitious" project being proposed

**Comment by paparai** [comment]
> Apologies, I mean no offense, but seriously...what other conclusion should I draw? I hope this is dealt with soon. This is not an acceptable issue for such an "ambitious" project being proposed

Bro, they do not care because it is their way to protect from "siblings". It will be great if we will get an answer here and issue will not be closed.

**Comment by goodwaygg44** [comment]
> @NicoSerranoP it did not work for me and my friends. we have the same issue .
> 0x1F70eBBd87dbE62f323864c982f89C9E81539574
> this is my address. should i provide you my friends' addresses too? should they just sign up github account to contact you themselves or i can do them favour. like 5 of them have the issue

@NicoSerranoP it did not work for me and my friends. we have the same issue .
0x1F70eBBd87dbE62f323864c982f89C9E81539574
this is my address. should i provide you my friends' addresses too? should they just sign up github account to contact you themselves or i can do them favour. like 5 of them have the issue

**Comment by goodwaygg44** [comment]
> Hi there! Could you try one more time this week? If it does not work, please send your public address here so we can manually whitelist it

@NicoSerranoP it did not work for me and my friends. we have the same issue .
0x1F70eBBd87dbE62f323864c982f89C9E81539574
this is my address. should i provide you my friends' addresses too? should they just sign up github account to contact you themselves or i can do them favour. like 5 of them have the issue

**Comment by goodwaygg44** [comment]
it is very frustrated. i tried with new wallet. it almost success. but it turned to "something wrong" during contribution. and same thing happened. said the address contributed before. what is wrong exactly ?? no connection issue

**Comment by goodwaygg44** [comment]
<img width="935" alt="Screenshot 2023-02-19 at 9 35 38 PM" src="https://user-images.githubusercontent.com/123880103/219951656-6b955e5b-d496-431d-8744-3a0578e56d29.png">

**Comment by goodwaygg44** [comment]
<img width="935" alt="Screenshot 2023-02-19 at 9 36 33 PM" src="https://user-images.githubusercontent.com/123880103/219951717-afa6c929-db5c-445f-853a-42b0ed797a7e.png">
what is the problem exactly?
connection has no issue though.

**Comment by Taosome** [comment]
I got the same problem. I wait for my turn almost 18 days. Today, it tell me SOMETHING WENT WRONG. However, i even can't join the lobby!
Here is my wallet address:
0xb4AFe7d7323452965AEeCdB44304F7d2781d25e7
pls help me, sir? @NicoSerranoP

**Comment by rossimrco** [comment]
Hi @NicoSerranoP , I'v the same issue. Could you please remove me from blacklist? 0xaf42659B804d3C042311A65195cB6566a96b4135
Thanks in advance

**Comment by gaohongxiang** [comment]
> @89kkkkk @hehnajd @fokwiz @bettyy0999 @gaohongxiang您的地址已从黑名单中删除。请再试一次

Is there any new progress? When can our address be removed from the blacklist? It's not fair to people who have waited so long. Only 15 days left. this is my address, thanks。0x494e3aD6DC1E9070bE09E054bFb809905F95C9F6

**Comment by Sweetilona3** [comment]
Kas tas ir?

**Comment by shaoguos** [comment]
I got same error when it was my turn to contribute. Here is my wallet

0xbF58228D2312Fde6B61fa068f462Af5CcA1eBd91

**Comment by NicoSerranoP** [comment]
@hehnajd @gaohongxiang @paparai @zzyspace @Mogulcc @goodwaygg44 @Taosome @rossimrco your addresses have been removed from the blacklist. Please a couple of things to consider: 

1. Your upload time should be at least 30Mbps

2. You need to pay attention from time to time to your browser (if it goes to sleep mode when the sequencer choose you you could lose your chance)

3. You can use another client implementations to avoid worrying about these constrains

4. We are not offering any kinds of airdrops nor economic incentives. Your participation allows you to contribute into scaling Ethereum through sharding. We will deliver POAPs afterwards but they are just a recognition item (do not have value).


We apologize for the inconveniences but the blacklist allows us to protect against bot attacks (even though bots have found clever ways to avoid it and right now the lobby is super packed with them). We are discussing the possibility to reopen the general contributions after the special contributions period. So if you don't get a chance until March 13th, you could try it later.

I will close this issue for internal organization. In case you get blacklisted again, please open a new issue :)
