### ISSUE TITLE
call ｀contribute｀ failed

### ISSUE THREAD

**Issue by zzyspace** [zkparty/trusted-setup-frontend#161]
It said ｀not your turn to contribute｀, and UI said ｀Something went wrong｀. When I login again, the issue same to #158 #159

**Comment by NicoSerranoP** [comment]
Could you try again one more time this week? If it does not work, send me your public address through here so we can whitelist it

**Comment by zzyspace** [comment]
@NicoSerranoP I tried, still not work. can u whitelist it, please? thx!
address: 0x52A4249BaFF6832e336E6aF8d6a50cBA106eeE11
