### ISSUE TITLE
Is it normal to see "another contribution in progress"?

### ISSUE THREAD

**Issue by feilun-feilun** [zkparty/trusted-setup-frontend#163]
“WAITING TO BESUBMITTED” for some days.
Get thousands of “another contribution in progress” and no error message. I'm not sure whether it's right.
<img width="376" alt="截屏2023-02-09 下午12 44 48" src="https://user-images.githubusercontent.com/49551621/217720229-39a91f5e-814c-476f-b1ac-0c2b33fc8deb.png">
Please let me know if there is something wrong. Thank you.

**Comment by NicoSerranoP** [comment]
Hi there! Yes it is right, the lobby is currently packed therefore it might take a couple of days for the sequencer to choose you

**Comment by feilun-feilun** [comment]
Thanks.
