### ISSUE TITLE
"The web application is using an invalid authorization code. Please report it on Github" error

### ISSUE THREAD

**Issue by pggallagher** [zkparty/trusted-setup-frontend#171]
I am using the brave browser with MM. My address has more than enough past tx history too. Thanks for any and all help! Hoping to fix this and help contribute.

![image](https://user-images.githubusercontent.com/40184484/221759485-ef3eb3e5-788c-4cdf-8ba5-24ed4772fe2c.png)

**Comment by NicoSerranoP** [comment]
Hi there! That error code is related to Github and it might be caused because of a network drop. Could you try again in a chromium-based browser and let me know if it works? 

Remember that if you login with Github, you do not have to use Metamask or any other wallet
