### ISSUE TITLE
At the computation step, the text refers to `the Sequencer` doing the work. This should be corrected.

### ISSUE THREAD

**Issue by glamperd** [zkparty/trusted-setup-frontend#19]
Suggested: 'your random inputs are being combined with others'

**Comment by NicoSerranoP** [comment]
The text has been changed (don't remember on what exact PR but it was done in the Devcon week). Check it out here: [src/pages/contributing.tsx Line 160](https://github.com/zkparty/trusted-setup-frontend/blob/main/src/pages/contributing.tsx#L160).
