### ISSUE TITLE
Hi, I can't find my address record, I think there is an error. please help me

### ISSUE THREAD

**Issue by vip826424** [zkparty/trusted-setup-frontend#192]
0x15B3f1a902bC2bf9c1749f2CB2263d5c4700A0d0 
Hi, I can't find my address record, I think there is an error. please help me

**Comment by vip826424** [comment]
![image](https://github.com/zkparty/trusted-setup-frontend/assets/84230754/2302084f-8626-4b9d-ba42-1be33af36d8b)

**Comment by NicoSerranoP** [comment]
The blacklist has been reset. Please try again
