### ISSUE TITLE
Update IPFS Frontend

### ISSUE THREAD

**Issue by sigmachirality** [zkparty/trusted-setup-frontend#194]
Update IPFS-hosted mirror of the frontend to allow contributions. Currently the IPFS frontend is still stuck in the special contributions period (as shown by the negative number of days)

<img width="830" alt="Screen Shot 2023-06-24 at 4 42 05 PM" src="https://github.com/zkparty/trusted-setup-frontend/assets/2645695/da1625e3-9e72-4dbe-9754-16b33e9594d8">

**Comment by glamperd** [comment]
Updated IPFS deployment can be found at https://ipfs.io/ipfs/QmPmSNavao8AGXKGERwh7Ce5zHSZbw7PzU6xcqkVpsaCTQ/

Use tag IPFS_v4 if building from source
