### ISSUE TITLE
"This address has already contributed to the Ceremony"

### ISSUE THREAD

**Issue by wslove520** [zkparty/trusted-setup-frontend#195]
Hello I was participating in the Ceremony, I was the only one in the hall, and I was prompted to be selected, but I was stuck on that page for a long time and there was an error, then I checked the contribution record and I was not there, so I rejoined the Ceremony and the page said **"This address has already contributed to the Ceremony"**. Can you help me with this? I think this is a big ETH event with 110,000 people and I don't want to miss it.
**My address is:0x0884d9cbeddf1e34db175f80582cc05dbb211799**
I appreciate it!
@NicoSerranoP 
![image](https://github.com/zkparty/trusted-setup-frontend/assets/108172764/e17d7f95-1d18-4cc7-b4a5-356d6e482703)

**Comment by NicoSerranoP** [comment]
The blacklist has been reset. Please try again
