### ISSUE TITLE
This address has already contributed to the Ceremony

### ISSUE THREAD

**Issue by xalexec** [zkparty/trusted-setup-frontend#198]
when I contribution,my computer hibernates please help @NicoSerranoP

0x4bffcec17ef99f452e3fd3a6ce22c810e44870b5
0xef9659a280155f3344cdbcb51e1275f4c29af8b0

**Comment by xalexec** [comment]
I think maybe I'm using an iPhone hotspot,iPhone turn off the network

**Comment by huangyunxin** [comment]
0x2ef981cdcfed8f6aef982e9065f0815395b71499 Please help me remove the blacklist too, thanks @NicoSerranoP

**Comment by Fernando07654328664** [comment]
Android
ola

**Comment by Fernando07654328664** [comment]
Ola

**Comment by NicoSerranoP** [comment]
Guys we are not going to clean the blacklist anymore :( try to contribute with your Github profiles

**Comment by xalexec** [comment]
> Guys we are not going to clean the blacklist anymore :( try to contribute with your Github profiles

WHY? I see a lot of people report this issue, And can remove or reset,I'm not robot...
