### ISSUE TITLE
Entropy text field causes browser to try to remember password. 

### ISSUE THREAD

**Issue by glamperd** [zkparty/trusted-setup-frontend#22]
This is bad for UX and defeats the purpose of deleting the secret (should a user actually save the password.

**Comment by tkmct** [comment]
I agree, currently, we're using `type=password` to hide the content of the input for ease. instead, we should use some javascript to hide the content.

**Comment by NicoSerranoP** [comment]
I fixed it in Chrome and working on it in Firefox :)
