### ISSUE TITLE
Contribute via Github

### ISSUE THREAD

**Issue by cutemoon1814** [zkparty/trusted-setup-frontend#220]
**Is there a way we can claim poap if we contributed through our github?**

![Screenshot (1748)](https://github.com/zkparty/trusted-setup-frontend/assets/97695550/500f7229-ad25-4a7f-883a-6d89dbbba290)

**Comment by NicoSerranoP** [comment]
Sadly no, you cannot get a POAP with Github. POAP does not allow us to verify participants through Github. It was stated in the FAQs in the [main page](https://ceremony.ethereum.org/)

![image](https://github.com/zkparty/trusted-setup-frontend/assets/38594836/edb25110-6a80-43aa-8fe7-f1db5659209f)


It is worth pointing out that the transcript will keep your Github contribution for all eternity so you can show everyone that you participated and that your contribution is inside the transcript.
