### ISSUE TITLE
Landing page tweaks

### ISSUE THREAD

**Issue by tvanepps** [zkparty/trusted-setup-frontend#29]
![image](https://user-images.githubusercontent.com/27454964/197031654-88f90e4c-c749-4f6a-ae55-7643c6acec09.png)

I am viewing this with chrome on windows

- the white nav bar should not overlap with the blue decorative border
- there is still a horizontal scrollbar even when the zoom is at 100%
- body text should be left aligned, not centered
- does "Unlock" need to be visible if it just takes contributors to the next page?

**Comment by NicoSerranoP** [comment]
All these observations have been addressed in [nico-30-signin-fixes branch](https://github.com/zkparty/trusted-setup-frontend/tree/nico-30-signin-fixes). I will merge it as soon as possible
