### ISSUE TITLE
UI to view my contribution

### ISSUE THREAD

**Issue by ChialiTsai** [zkparty/trusted-setup-frontend#44]
design coming soon

**Comment by NicoSerranoP** [comment]
https://www.figma.com/file/PxzmldIzJ6hLkNZxWnXtnH?node-id=1474:399212#296725392

**Comment by wackerow** [comment]
Oops, realizing this is here... I had opened #56 which turns out to be a duplicate of this issue. 

PR #66 implements this based on above designs (though it keeps the color theme of the site in its current form). I will update that PR to reference this issue and close my duplicate.

**Comment by NicoSerranoP** [comment]
Closes in #77
