### ISSUE TITLE
Add simplified language option

### ISSUE THREAD

**Issue by wackerow** [zkparty/trusted-setup-frontend#57]
### Objective
Provide two options for the theme of the copy throughout the process. The primary text currently in place tells a story and uses language that makes the experience enjoyable. A second option with more simplified language and explanation would help towards the goal of enabling as many people as possible to be able to understand and participate in this ceremony.

### Design considerations
This could potentially be treated in the code as another "locale" or "language". On the front-end we should consider better ways to handle this beyond just doubling the list length for the language dropdown. A toggle that switches between the two modes for whatever language the user is on could be appropriate.

**Comment by NicoSerranoP** [comment]
https://notes.ethereum.org/@CarlBeek/HJKULRfro
