### ISSUE TITLE
Mobile functionality

### ISSUE THREAD

**Issue by wackerow** [zkparty/trusted-setup-frontend#58]
## Description

The current interface stops users from mobile devices from experiencing the website at all. Part of this is due to concerns over hardware performance, and potential browser session timeouts on mobile. 

If it is decided to not allow contributions from mobile, I think we could still generate some wins by at least enabling the core of the site for mobile users, which is to include an additional FAQ page (#55) and View contributions page (#56). This will allow a mobile user to at least learn a bit about what is going on, even if they are unable to contribute directly from their mobile device.

If we end up not restricting mobile devices from participating, we need to consider easier ways for user to input entropy, as it would currently involve tapping quite a bit. This may also include small updates to the copy explaining that step.

## Objectives
- [x] Remove mobile device redirect from all pages, and only redirect mobile users if they try to go to a path of any contribution step. #63 
- [x] Improve mobile responsive design to make content accessible on all screen sizes #59

Optional items to consider:
- Consider hamburger menu to include network status, optionally connected address, language selector, FAQ, and view contributions links
- If language selector kept visible from Header on mobile, consider reducing to only using language short-code, ie "en" instead of "English". Or just hide language name, leaving the globe icon and down chevron.

Also,
- [x] Work out which, if any, devices should be blocked from utilizing the app based on performance of timeout limitations
If we don't restrict mobile devices: (Update, mobile devices will be restricted)
- ~~Add new method of obtaining entropy from a mobile device~~
- ~~Update explainer copy for this step (Would need to be translated as well)~~

**Comment by NicoSerranoP** [comment]
Hey Paul @wackerow! I just merged the `wackerow/responsiveness` branch, does it close this issue?

**Comment by wackerow** [comment]
@NicoSerranoP Not yet, but it checks one of them off =)

**Comment by samajammin** [comment]
Curious to hear input on this but for now I'd propose we cut mobile support from an initial production release. Seems like there's enough things to work on to make this app production-ready for desktop across various browsers.

Does anyone have strong conviction that people will actually be using this from their phones? Or is that more of a nice-to-have?

I suggest we strongly consider shipping with just a desktop app, then see how many people try to actually perform the ceremony on their phone. e.g. perhaps we style the homepage for mobile, then measure how many people on mobile devices click "begin".
Maybe to start we push folks to desktop like on the [Staking Launchpad](https://launchpad.ethereum.org/en/overview):
![Image 2022-11-08 at 8 57 56 PM](https://user-images.githubusercontent.com/8097623/200917462-78b7823b-7510-434e-a0c9-e32f85943a5e.jpg)

**Comment by wackerow** [comment]
The page currently displays a page like this for mobile devices (a for mobile device agents is performed, and users are then routed to `/mobile` which is a component similar to above. 

<img width="843" alt="image" src="https://user-images.githubusercontent.com/54227730/200921352-5e51d51e-71df-4dc5-aa34-f9106f05c843.png">

PR #63 introduces one possibility to handle this differently, but enabling certain paths to be viewed on mobile, but the button to start is disabled (and directly going to the ceremony URL paths will kick them back):

<img width="938" alt="image" src="https://user-images.githubusercontent.com/54227730/200922191-af085726-468d-41d3-8e40-9f9ea0c7ccb3.png">

If we decide to not go with supporting mobile for the actual ceremony, I propose this as an alternative so users visiting on mobile can still access the landing, faq and records pages, and also gain access to the footer links if they like (vs being hit with a wall)

**Comment by wackerow** [comment]
For a number of factors, it sounds like included mobile devices in the ceremony is not going to work out. As such I've updated the original post, removing todo's related to enabling mobile devices. Also pulled a couple items out as optional. 
Hiding the languages on mobile could be a simple win, but not necessarily critical. Open to discussion, but in the meantime I'm going to call this issue complete.
