### ISSUE TITLE
URL of the sequencer is not same as the frontend

### ISSUE THREAD

**Issue by potuz** [zkparty/trusted-setup-frontend#94]
When signing on a url from `ethereum.org` with metamask, it prompts

```
You are signing-in to kzg-ceremony-sequencer-dev.fly.dev.
```
Which is the url of the sequencer. This discrepancy makes users like me worried and scared of signing anything with my wallet.

**Comment by NicoSerranoP** [comment]
Hi @potuz ! You are completely right. We are in the process of moving the sequencer in a `ethereum.org` subdomain. It is not going to be the same as the `ceremony.ethereum.org` domain but it something like `sequencer-ceremony.ethereum.org`

**Comment by NicoSerranoP** [comment]
I just updated the production web app with the sequencer.ceremony.ethereum.org URL for the sequencer API. Check it out here: [https://ceremony.ethereum.org/](url)
