### ISSUE TITLE
UI Comments on the Records Page

### ISSUE THREAD

**Issue by tvanepps** [zkparty/trusted-setup-frontend#95]
1.  - [x] elsewhere in the copy we use "Contribution" not "Record". in the past we discussed those and "Transcript". we should pick one and be consistent, I dont have a strong preference, could even be "Contribution Records" or "Contribution Transcript" for the title. If needed, the FAQ should be updated to reflect our decision here.
2.  - [x] What is the sequencer address and why do users need to see it here?
3. - [x] the search field has too many components and cuts off whatever appears after "#". Either we need to remove that last element, widen the search bar, or shorten some of the other text elements. Also, somewhere we had discussed not using ENS bc it might change in the future - is that still the case?
4. - [x] what is "Seq. #"? if sequence, it's not clear bc we also use Sequencer in the docs and specs. i think it should just be "#" or nothing, it's pretty clear what that column refers to
5. - [x] why is the word "Specification" here? if not needed it should be removed. in the "view" modal, it's called "Participant ID", which might be better for consistency
6. - [x] i should be able to click anywhere within the red box to access the "Contribution Details" modal that is accessible when clicking "View". when a cursor is within the red box, can we do a very simple hover animation like we have for other buttons and turn the cursor into a hand? if this can be done, we can remove the "Details/ view" column entirely. otherwise the "view" is redundant. (not a strong opinion if there is good reason to keep it)
7. - [x] Why would a user need to click into the individual "PoT Pubkeys" from here? can we move this expand interaction to the modal that comes when clicking "view"? Also, can we put the 4 identicons in a horizontal line instead of 2X2 to compress records vertically? (if it stays as a 2X2, thespace between the top and the bottom identicons should be the same)
8.  - [x] why is there a horizontal scroll here? should not appear at 100% zoom
9. - [x] how is it possible there are two contributions from stefan via github? i thought we were filtering for duplicate contributions from the same participant.

![image](https://user-images.githubusercontent.com/27454964/205373923-1bca82ca-fa77-486d-883c-8f893969281f.png)

**Comment by tvanepps** [comment]
Generally, it's hard to know what this modal needs to tell users - should they be saving the info locally? we should consider adding some tooltips next to each header 🛈 that expands with info on hover, or just include all info next to the header by default.

1. the "x" appears differently when next to text vs a number
2.  "Pot" is not useful. Should either say "Powers of Tau" or be omitted
3. Can we reproduce the identicons here next to their pubkey to show the link? if we do this, make sure the image is aligned with the left side of the header text above
4.  "Sequence #" (or whatever it's changed to on the screen before) should also appear on this modal below "Contribution Details" - possibly with ←→ toggle so users can cycle through many contributions without having to exit and reenter this modal every time. the toggle arrows are a lower priority tho

![image](https://user-images.githubusercontent.com/27454964/205376809-48156f5c-9fcb-4bd0-a532-f2f2d1deff32.png)

**Comment by tvanepps** [comment]
1. There should be a an action suggestion for each of the numbers/ arrow when i hover it should change to the hand cursor and be underlined/ drop shadowed
2. the footer is just a little too large. can we shrink it vertically to about the size of the red rectangle?
3. We will have 2 audit reports, maybe there needs to be separate links to the Implementation report and the sequencer audit? or just remove this link and send users to the documentation where they can find both
![image](https://user-images.githubusercontent.com/27454964/205378353-862096cb-7085-4bcb-a92b-a65c436f3133.png)

**Comment by tvanepps** [comment]
thanks for the clarifications/info. these generally make sense

2. we probably need a guide for how users should verify contributions. see the namada trusted setup "Verify Contribution" button, instructions [hosted on github](https://github.com/anoma/namada-trusted-setup#verify-a-contribution). what would verification look like for our ceremony? eg. hosted on the interface itself vs. or another repo, what steps would the user need to complete, etc

3. makes sense. we might need a tooltip for this to explain why unique identicons are important / what they signify

9. makes sense, carl also explained why this is the case. we should definitely start with a clean slate when the time comes

10. sounds good, we will need to upload the completed report to the kzg repo when it's produced and point to that one

**Comment by PlasmaPower** [comment]
One other UI consideration: If you're on e.g. the second page of contributions, and then you search for a particular address, it won't show up until you click the "1" at the bottom to jump back to the first page, which confused me at first.

**Comment by NicoSerranoP** [comment]
@tvanepps regarding the blockies, which option do you prefer? 

1. ![image](https://user-images.githubusercontent.com/38594836/206358572-b1c6e42f-09fd-498e-bc4c-1cf941850b6e.png)

2. ![image](https://user-images.githubusercontent.com/38594836/206358620-234e3d35-d271-41e9-84f2-1738889ee883.png)

**Comment by glamperd** [comment]
Further to point 3: We should add to the tooltip text the value of the pubkey in hex, and the sub-contribution to whiuch it applies, e.g. '2^12'

**Comment by glamperd** [comment]
In the popup that shows the pubkey when you click the blockie, in Records page: I suggest the title should be ''Powers of Tau public key', and mention which sub-contribution it's for, e.g. 2^12
