### ISSUE TITLE
Unknown field `ecdsaSignature` expected ecdsa_signature (wrapper_small_pot.js)

### ISSUE THREAD

**Issue by martinlsanchez** [zkparty/trusted-setup-frontend#98]
I guess this should be an easy fix, let me know if I can help you in something or you need any more information.

It's easy repeatable, here an screenshot of the console with some context. 

![image](https://user-images.githubusercontent.com/1659075/205760020-56faa689-325a-40cb-8648-e660d31ee477.png)

Maybe it's just an update to the latest version of the lib. :-)

**Comment by NicoSerranoP** [comment]
Hey @martinlsanchez ! :) sorry for the delay, thank you very much for this. I updated the version in an [open PR](https://github.com/zkparty/trusted-setup-frontend/pull/97). I hope we get it merge today or tomorrow and it would automatically deploy in the production site.

If you find any issues please post them here so we can take a look.
